### ISSUE TITLE
Qt backend and DockWindow and DockableViewElement

### ISSUE THREAD

**Issue by rosoba** [enthought/pyface#263]
I used the DockWindow feature in the past, when wx was the primary backend.
After switching to Qt as recommended, this feature seems to be obsolete, am I right? 
In the demo examples located here 
https://github.com/enthought/pyface/tree/master/examples/dock
wx  toolkit is being used. **My question is:** 
- Did  I miss some hint how to activate this feature for Qt backend?
- Is it likely that the Dock-feature will be supported for Qt backend
in future? 
Many thanks.

**Comment by corranwebster** [comment]
DockWindow is not supported at all for the Qt backend and is unlikely to be.  It's not exactly deprecated, since it's important for the Wx backend for TraitsUI and Workbench (and hence Mayavi) but we're not actively developing it at the moment.  A large part of the reason for DockWindow existing isn't needed for Qt, since the Qt `QMainWindow` class already comes with docking functionality, although not quite all the features of DockWindow.

You might look at using Tasks for your use-case https://github.com/enthought/pyface/tree/master/pyface/tasks

**Comment by corranwebster** [comment]
Closing this issue, since I think the question is addressed.  Feel free to re-open if needed.
