### ISSUE TITLE
Add PyQt as an expected failure in CI matrix

### ISSUE THREAD

**Issue by rahulporuri** [enthought/pyface#627]
It looks like we're seeing a lot of segfaults (A LOT) with the move to rh7 and PyQt4 4.12.1-1. See PR https://github.com/enthought/pyface/pull/618. Given this, we will want to mark PyQt as an expected failure on travis and appveyor - along with enabling #620 to get information on why things are failing.

https://github.com/enthought/pyface/blob/8dc1d16c797d56752719060fcab9c601ce12065a/appveyor.yml#L16-L20

see example from traitsui for travis config - https://github.com/enthought/traitsui/blob/796bdb973cc3f2c77eb3097ff9f2e8b8f86ff11c/.travis.yml#L24-L27

**Comment by kitchoi** [comment]
It will be harder to notice breakages for PyQt4 if it is marked as expected failure. The CI for PyQt4 was brought back because there are still projects using PyQt4. If there are projects using PyQt4 and that it is incompatible with RH7, then it is likely those projects are not using RH7 either. I'd propose we _don't_ make PyQt4 build an expected failure but instead avoiding switching to RH7.  Is there a particular why we must switch from RH6 to RH7?

**Comment by kitchoi** [comment]
See https://github.com/enthought/pyface/issues/518

**Comment by rahulporuri** [comment]
> Is there a particular why we must switch from RH6 to RH7?

Nope. But I would really like us to use the latest and greatest edm. One option here is to check and explicitly pass `--platform` for linux and set it to rh6 instead of rh7.

**Comment by kitchoi** [comment]
See the platform `--platform` explicitly as rh6 sounds like the right solution.

**Comment by rahulporuri** [comment]
closing as we don't test against PyQt anymore
