### ISSUE TITLE
Replace use of pkg_resources with importlib_metadata

### ISSUE THREAD

**Issue by corranwebster** [enthought/pyface#789]
Python 3.8 introduces standard library code for entrypoint handling via the `importlib.metadata` module.  This is back-ported to earlier versions of Python via [`importlib_metadata`](https://importlib-metadata.readthedocs.io/en/latest/index.html).

This should give better forward compatibility, and may help people who want to freeze Pyface/TraitsUI apps.

**Comment by rahulporuri** [comment]
Using `importlib.metadata` instead of `pkg_resources` also improves startup time.

```
❯ python -Ximporttime -c "import importlib.metadata"
import time: self [us] | cumulative | imported package
...
import time:      6528 |     141065 | importlib.metadata

❯ python -Ximporttime -c "import pkg_resources"
import time: self [us] | cumulative | imported package
...
import time:     28439 |     441931 | pkg_resources
```

I consistently see 400-450 ms for `pkg_resources` vs 100-150 ms for `importlib.metadata`. Note that this is with python 3.8.6. I mostly see the same numbers on python 3.9.

**Comment by rahulporuri** [comment]
@corranwebster i've added this to the Q4 2020 sprint backlog, in hopes that we can find time to address this before the end of the quarter.

**Comment by mdickinson** [comment]
Current uses of `pkg_resources` fall into two different categories: resource location and entry-point enumeration - we'll need `importlib.resources` rather than `importlib.metadata` for the first.

Last time we looked at `importlib.resources`, it had issues (namely that data directories had to be full-blown Python packages for things to work). That's changed since Python 3.9, and in the `importlib_resources` backport, so it may be worth another look.

**Comment by kitchoi** [comment]
#790 only resolves half of the usage of `pkg_resources`, we still have #791 pending.

**Comment by rahulporuri** [comment]
closing as #791 is also merged.
